{{- if .Values.build.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "example-app-helm.fullname" . }}
  labels:
    {{- include "example-app-helm.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
{{- end }}