apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: httpd-example
    template: httpd-example
  name: httpd-example
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: httpd-example:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/sclorg/httpd-ex.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:2.4-el8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ImageChange
    - type: ConfigChange
