apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-helm
spec:
  destination:
    namespace: httpd-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/example-app-helm
    repoURL: https://github.com/sabre1041/k8s-manifest-validation.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
